{% set name = "jupyterlab_code_formatter" %}
{% set version = "3.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 55adb8fa8b9bd58f0b39e7d3ead6c1e862e9ebc1444a66cdb4233d8dc6351d4b

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatchling >=1.4.0
    - hatch-nodejs-version
    - hatch-jupyter-builder >=0.5
    - python {{ python_min }}
    - pip
  run:
    - jupyter_server >=1.21,<3
    - python >={{ python_min }}

test:
  imports:
    - jupyterlab_code_formatter
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/jupyterlab-contrib/jupyterlab_code_formatter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A universal code formatter for JupyterLab.

extra:
  recipe-maintainers:
    - krassowski
    - dbast
    - xhochy
