{% set name = "jupyterlab_code_formatter" %}
{% set version = "1.0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/ryantam626/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 1501680d9e72cde36f410839142bf2e7fc9cfd795248ff9f6a7859d7d1c7e03e

build:
  number: 0
  noarch: python

requirements:
  build:
    - nodejs
  host:
    - jupyterlab >=1
    - pip
    - python >=3.6
  run:
    - jupyterlab >=1
    - nodejs
    - packaging
    - python >=3.6

test:
  imports:
    - jupyterlab_code_formatter

about:
  home: https://github.com/ryantam626/jupyterlab_code_formatter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A universal code formatter for JupyterLab.

extra:
  recipe-maintainers:
    - dbast
    - xhochy
